APPIOS-2737, APPIOS-2767: Optimize SDK
paysera/swift-lib-wallet-sdk pull request #31
Opened 2021-03-03 15:42 UTC by Pattio

2021-03-04 04:54 UTC, softwaresaiyajin reviewed
I've run some test cases for both wallet and auth clients, expected results were met.

2021-03-04 04:54 UTC, softwaresaiyajin commented on Sources/PayseraWalletSDK/Services/WalletAsyncClient/RefreshingWalletAsyncClient.swift
> +        }
Do you think we should refactor this? These are duplicate lines from `BaseAsyncClient`, I know that `RefreshingWalletAsyncClient` is bit different since it has to consider the token expiry.

2021-03-08 11:49 UTC, Pattio commented on Sources/PayseraWalletSDK/Services/BaseAsyncClient.swift
>      let publicWalletApiClient: PublicWalletApiClient?
Yes, done

2021-03-08 11:49 UTC, Pattio commented on Sources/PayseraWalletSDK/Services/WalletAsyncClient/RefreshingWalletAsyncClient.swift
> +        }
Agree, done

2021-03-09 03:30 UTC, softwaresaiyajin requested changes

2021-03-09 03:30 UTC, softwaresaiyajin commented on Sources/PayseraWalletSDK/Services/BaseAsyncClient.swift
> +            let expiredTokenHandler = expiredTokenHandler
I think `let expiredTokenHandler = expiredTokenHandler` should be the first condition so `error` and `statusCode` don't need to be evaluated when it's nil

2021-03-09 06:15 UTC, mildamauricaite approved these changes

2021-03-09 07:32 UTC, Pattio commented on Sources/PayseraWalletSDK/Services/BaseAsyncClient.swift
> +            let expiredTokenHandler = expiredTokenHandler
I don't agree due to following:
1. `400` error code is not standard expiration code and is only used in certain cases, which means that other error codes will be more likely and `statusCode` should short circuit more often (especially in `RefreshingClient` which always has expiration handler and is used for majority of requests).
2. I think it feels more natural when reading, as it follows the structure of condition above (furthermore, the main cause of the check is `statusCode` not handler) and it naturally suggest that once another handling of status code is added this should probably be refactored to `switch` on `statusCode`

2021-03-09 07:41 UTC, softwaresaiyajin approved these changes

2021-03-09 08:14 UTC, merged